/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.cphbusiness.sem4.view;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ultroman
 */
public class Login extends JPanel{

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void giveCommandToParentJFrame(String command){
        ValgFagsJFrame temp = (ValgFagsJFrame)SwingUtilities.getWindowAncestor(this);
        temp.actuateCommand(command);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(894, 572));
        setMinimumSize(new java.awt.Dimension(894, 572));
        setName("Login");
        setPreferredSize(new java.awt.Dimension(894, 572));
        setLayout(null);

        jButton1.setText("Studerende");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(93, 110, 300, 260);

        jButton2.setText("Uddannelseskoordinator");
        jButton2.setMaximumSize(new java.awt.Dimension(89, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(89, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(89, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(410, 110, 300, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        giveCommandToParentJFrame("GOTO_StudLogin");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        giveCommandToParentJFrame("GOTO_UDKLogin");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
