/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.cphbusiness.sem4.view;

import dk.cphbusiness.sem4.model.DTO.ValgfagsDTO;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ultroman
 */
public class StudValgfagsRunde1 extends JPanel {
    
    ArrayList<ValgfagsDTO> valgfagsListe;
    
    /**
     * Creates new form Login
     */
    public StudValgfagsRunde1(ArrayList<ValgfagsDTO> valgfagsListe) {
        this.valgfagsListe = valgfagsListe;
        initComponents();
        jList_Valgfag.setModel(new DefaultListModel());
        jList_Valgfag.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jList_1prioriteter.setModel(new DefaultListModel());
        jList_2prioriteter.setModel(new DefaultListModel());
        
        for (ValgfagsDTO valgfagsDTO : valgfagsListe) {
            ((DefaultListModel)jList_Valgfag.getModel()).addElement(valgfagsDTO.getNavn());
        }
    }
    
    public ArrayList<ValgfagsDTO> getValgfagsListe() {
        return valgfagsListe;
    }
    
    public ArrayList<String> getValgteValgfag(){
        ArrayList<String> valgfag = new ArrayList<String>();
        valgfag.add((String)jList_1prioriteter.getModel().getElementAt(0));
        valgfag.add((String)jList_1prioriteter.getModel().getElementAt(1));
        valgfag.add((String)jList_2prioriteter.getModel().getElementAt(0));
        valgfag.add((String)jList_2prioriteter.getModel().getElementAt(1));
        return valgfag;
    }
    
    private void angivValgfagSom1Prioritet(){
        if(jList_1prioriteter.getModel().getSize()<2){
            String temp = (String) jList_Valgfag.getSelectedValue();
            if( temp != null )
            {
                ((DefaultListModel)jList_1prioriteter.getModel()).addElement(temp);	
                ((DefaultListModel)jList_Valgfag.getModel()).removeElement(temp);

                revalidate();
                repaint();
            }
        }
    }
    
    private void fjernValgfagFra1Prioriteter(){
        String temp = (String) jList_1prioriteter.getSelectedValue();
        if( temp != null )
        {
            ((DefaultListModel)jList_Valgfag.getModel()).addElement(temp);
            ((DefaultListModel)jList_1prioriteter.getModel()).removeElement(temp);

            revalidate();
            repaint();
        }
    }
    
    private void angivValgfagSom2Prioritet(){
        if(jList_2prioriteter.getModel().getSize()<2){
            String temp = (String) jList_Valgfag.getSelectedValue();
            if( temp != null )
            {
                ((DefaultListModel)jList_2prioriteter.getModel()).addElement(temp);	
                ((DefaultListModel)jList_Valgfag.getModel()).removeElement(temp);

                revalidate();
                repaint();
            }
        }
    }
    
    private void fjernValgfagFra2Prioriteter(){
        String temp = (String) jList_2prioriteter.getSelectedValue();
        if( temp != null )
        {
            ((DefaultListModel)jList_Valgfag.getModel()).addElement(temp);
            ((DefaultListModel)jList_2prioriteter.getModel()).removeElement(temp);

            revalidate();
            repaint();
        }
    }

    public void giveCommandToParentJFrame(String command){
        ValgFagsJFrame temp = (ValgFagsJFrame)SwingUtilities.getWindowAncestor(this);
        temp.actuateCommand(command);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Tilbage = new javax.swing.JButton();
        jLabel_Valgfag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Valgfag = new javax.swing.JList();
        jButton_1prioTil = new javax.swing.JButton();
        jButton_1prioFra = new javax.swing.JButton();
        jButton_2prioTil = new javax.swing.JButton();
        jButton_2prioFra = new javax.swing.JButton();
        jLabel_2prioritet = new javax.swing.JLabel();
        jLabel_1prioritet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_1prioriteter = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_2prioriteter = new javax.swing.JList();
        jButton_Accepter = new javax.swing.JButton();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_AngivEmail1 = new javax.swing.JLabel();
        jTextField_FagBeskrivelse = new javax.swing.JTextField();
        jLabel_bPulje = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(894, 572));
        setMinimumSize(new java.awt.Dimension(894, 572));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(894, 572));
        setLayout(null);

        jButton_Tilbage.setText("Tilbage");
        jButton_Tilbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TilbageActionPerformed(evt);
            }
        });
        add(jButton_Tilbage);
        jButton_Tilbage.setBounds(0, 0, 100, 30);

        jLabel_Valgfag.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Valgfag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Valgfag.setText("Valgfag");
        add(jLabel_Valgfag);
        jLabel_Valgfag.setBounds(30, 80, 130, 22);

        jList_Valgfag.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ValgfagValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Valgfag);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 130, 250);

        jButton_1prioTil.setText("===>");
        jButton_1prioTil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1prioTilActionPerformed(evt);
            }
        });
        add(jButton_1prioTil);
        jButton_1prioTil.setBounds(170, 150, 65, 23);

        jButton_1prioFra.setText("<===");
        jButton_1prioFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1prioFraActionPerformed(evt);
            }
        });
        add(jButton_1prioFra);
        jButton_1prioFra.setBounds(170, 180, 65, 23);

        jButton_2prioTil.setText("===>");
        jButton_2prioTil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2prioTilActionPerformed(evt);
            }
        });
        add(jButton_2prioTil);
        jButton_2prioTil.setBounds(170, 260, 65, 23);

        jButton_2prioFra.setText("<===");
        jButton_2prioFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2prioFraActionPerformed(evt);
            }
        });
        add(jButton_2prioFra);
        jButton_2prioFra.setBounds(170, 290, 65, 23);

        jLabel_2prioritet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_2prioritet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_2prioritet.setText("2. Prioritet");
        add(jLabel_2prioritet);
        jLabel_2prioritet.setBounds(260, 230, 110, 30);

        jLabel_1prioritet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_1prioritet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_1prioritet.setText("1. Prioritet");
        add(jLabel_1prioritet);
        jLabel_1prioritet.setBounds(260, 120, 110, 30);

        jList_1prioriteter.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList_1prioriteter.setVisibleRowCount(2);
        jList_1prioriteter.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_1prioriteterValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_1prioriteter);
        jList_1prioriteter.getAccessibleContext().setAccessibleDescription("");
        jList_1prioriteter.getAccessibleContext().setAccessibleParent(this);

        add(jScrollPane2);
        jScrollPane2.setBounds(250, 150, 140, 60);

        jList_2prioriteter.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList_2prioriteter.setVisibleRowCount(2);
        jList_2prioriteter.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_2prioriteterValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_2prioriteter);
        jList_2prioriteter.getAccessibleContext().setAccessibleParent(this);

        add(jScrollPane3);
        jScrollPane3.setBounds(250, 260, 140, 60);

        jButton_Accepter.setText("Accepter");
        jButton_Accepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccepterActionPerformed(evt);
            }
        });
        add(jButton_Accepter);
        jButton_Accepter.setBounds(440, 270, 110, 40);

        jTextField_Email.setText("brugernavn@gmail.com");
        add(jTextField_Email);
        jTextField_Email.setBounds(420, 220, 150, 30);

        jLabel_AngivEmail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_AngivEmail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AngivEmail1.setText("Angiv Email");
        add(jLabel_AngivEmail1);
        jLabel_AngivEmail1.setBounds(440, 180, 110, 40);

        jTextField_FagBeskrivelse.setEditable(false);
        jTextField_FagBeskrivelse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_FagBeskrivelse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FagBeskrivelseActionPerformed(evt);
            }
        });
        add(jTextField_FagBeskrivelse);
        jTextField_FagBeskrivelse.setBounds(30, 420, 270, 60);

        jLabel_bPulje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_bPulje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bPulje.setText("Beskrivelse");
        add(jLabel_bPulje);
        jLabel_bPulje.setBounds(30, 390, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TilbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TilbageActionPerformed
        // TODO add your handling code here:
        giveCommandToParentJFrame("GOTO_Back");
    }//GEN-LAST:event_jButton_TilbageActionPerformed

    private boolean validerValg(){
        if(jList_1prioriteter.getModel().getSize()==2 && jList_2prioriteter.getModel().getSize()==2){
            return true;
        }
        return false;
    }
    
    private boolean validerEmail(){
        String email = jTextField_Email.getText();
        if(email.contains("@")
        && email.substring(email.indexOf("@")).contains(".")
        && email.length()>9
        )return true;
        return false;
    }
    
    public String getEmail(){
        return jTextField_Email.getText();
    }
    
    public String getBeskrivelseFraDTOUdfraNavn (String valgfagsNavn){
        for (ValgfagsDTO valgfag : valgfagsListe) {
            if(valgfagsNavn.equals(valgfag.getNavn()))return valgfag.getBeskrivelse();
        }
        return "Ingen beskrivelse fundet.";
    }
    
    private void jButton_AccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccepterActionPerformed
        if(validerValg() && validerEmail()){
            giveCommandToParentJFrame("ACTION_RegistrerValgfagRunde1");
        }else{
            JOptionPane.showMessageDialog(null, "Du skal vælge 4 valgfag, og indtaste korrekt e-mail!");
        }
    }//GEN-LAST:event_jButton_AccepterActionPerformed

    private void jButton_1prioTilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1prioTilActionPerformed
        // TODO add your handling code here:
        angivValgfagSom1Prioritet();
    }//GEN-LAST:event_jButton_1prioTilActionPerformed

    private void jButton_1prioFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1prioFraActionPerformed
        fjernValgfagFra1Prioriteter();
    }//GEN-LAST:event_jButton_1prioFraActionPerformed

    private void jButton_2prioTilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2prioTilActionPerformed
        angivValgfagSom2Prioritet();
    }//GEN-LAST:event_jButton_2prioTilActionPerformed

    private void jButton_2prioFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2prioFraActionPerformed
        fjernValgfagFra2Prioriteter();
    }//GEN-LAST:event_jButton_2prioFraActionPerformed

    private void jList_ValgfagValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ValgfagValueChanged
        if(jList_Valgfag.getSelectedIndex()!=-1 && jList_Valgfag.getModel().getElementAt(jList_Valgfag.getSelectedIndex()) != null){
            jTextField_FagBeskrivelse.setText(getBeskrivelseFraDTOUdfraNavn((String)jList_Valgfag.getModel().getElementAt(jList_Valgfag.getSelectedIndex())));
            jList_1prioriteter.clearSelection();
            jList_2prioriteter.clearSelection();
        }
    }//GEN-LAST:event_jList_ValgfagValueChanged

    private void jTextField_BeskrivelseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BeskrivelseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BeskrivelseActionPerformed

    private void jTextField_FagBeskrivelseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FagBeskrivelseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FagBeskrivelseActionPerformed

    private void jList_1prioriteterValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_1prioriteterValueChanged
        if(jList_1prioriteter.getSelectedIndex()!=-1 && jList_1prioriteter.getModel().getElementAt(jList_1prioriteter.getSelectedIndex()) != null){
            jTextField_FagBeskrivelse.setText(getBeskrivelseFraDTOUdfraNavn((String)jList_1prioriteter.getModel().getElementAt(jList_1prioriteter.getSelectedIndex())));
            jList_Valgfag.clearSelection();
            jList_2prioriteter.clearSelection();
        }
    }//GEN-LAST:event_jList_1prioriteterValueChanged

    private void jList_2prioriteterValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_2prioriteterValueChanged
        if(jList_2prioriteter.getSelectedIndex()!=-1 && jList_2prioriteter.getModel().getElementAt(jList_2prioriteter.getSelectedIndex()) != null){
            jTextField_FagBeskrivelse.setText(getBeskrivelseFraDTOUdfraNavn((String)jList_2prioriteter.getModel().getElementAt(jList_2prioriteter.getSelectedIndex())));
            jList_Valgfag.clearSelection();
            jList_1prioriteter.clearSelection();
        }
    }//GEN-LAST:event_jList_2prioriteterValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_1prioFra;
    private javax.swing.JButton jButton_1prioTil;
    private javax.swing.JButton jButton_2prioFra;
    private javax.swing.JButton jButton_2prioTil;
    private javax.swing.JButton jButton_Accepter;
    private javax.swing.JButton jButton_Tilbage;
    private javax.swing.JLabel jLabel_1prioritet;
    private javax.swing.JLabel jLabel_2prioritet;
    private javax.swing.JLabel jLabel_AngivEmail1;
    private javax.swing.JLabel jLabel_Valgfag;
    private javax.swing.JLabel jLabel_bPulje;
    private javax.swing.JList jList_1prioriteter;
    private javax.swing.JList jList_2prioriteter;
    private javax.swing.JList jList_Valgfag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FagBeskrivelse;
    // End of variables declaration//GEN-END:variables
}
