/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.cphbusiness.sem4.view;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ultroman
 */
public class UDKMenu extends JPanel {

    /**
     * Creates new form Login
     */
    public UDKMenu() {
        initComponents();
        jLabel_DatabaseKontakt.setVisible(false);
    }

    public void giveCommandToParentJFrame(String command){
        ValgFagsJFrame temp = (ValgFagsJFrame)SwingUtilities.getWindowAncestor(this);
        temp.actuateCommand(command);
    }
    
    private void changeDatabaseLabelVisibility(){
        jLabel_DatabaseKontakt.setVisible(!jLabel_DatabaseKontakt.isVisible());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_DatabaseKontakt = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(894, 572));
        setMinimumSize(new java.awt.Dimension(894, 572));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(894, 572));
        setLayout(null);

        jButton1.setText("Tilbage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 0, 100, 30);

        jButton2.setText("Valgfagsrunde 1");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(150, 120, 150, 60);

        jLabel_DatabaseKontakt.setBackground(new java.awt.Color(102, 255, 51));
        jLabel_DatabaseKontakt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_DatabaseKontakt.setText("Kontakter databasen...");
        add(jLabel_DatabaseKontakt);
        jLabel_DatabaseKontakt.setBounds(290, 0, 230, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        giveCommandToParentJFrame("GOTO_Back");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        giveCommandToParentJFrame("GOTO_UDKValgfagsRunde1");
        changeDatabaseLabelVisibility();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        changeDatabaseLabelVisibility();
    }//GEN-LAST:event_jButton2MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_DatabaseKontakt;
    // End of variables declaration//GEN-END:variables
}
